#!mupfel
AOBJS1="aldiv.o almul.o alrem.o lrem.o lmul.o ldiv.o uldiv.o"
AOBJS2="blivot.o salloc.o setjmp.o stkcpy.o xsignal.o abort.o trap.o"
COBJS1="atof.o atoi.o ceil.o etoa.o fabs.o ffptof.o floor.o"
COBJS2="fmod.o ftoa.o ftoffp.o ftol.o ltof.o printf.o fprintf.o xdoprtfp.o prtld.o"
COBJS3="prtint.o prtshort.o ctype.o fopen.o getl.o getw.o xmain.o xwmain.o optoff.o"
COBJS4="doprt.o puts.o fgetc.o filbuf.o read.o readasc.o readbin.o creat.o exit.o"
COBJS5="cleanup.o fclose.o close.o fdecls.o fflush.o open.o lseek.o fputn.o fputc.o"
COBJS6="flsbuf.o isatty.o malloc.o mallocnd.o sbrk.o blkfill.o write.o wrtchr.o channels.o"
COBJS7="writeasc.o writebin.o xopen.o blkio.o xread.o xwrite.o errno.o"
COBJS8="strcpy.o strcat.o strlen.o strcmp.o stricmp.o"
OPTIONOBJS="nofloat.o nottyin.o nostart.o nodisk.o nolong.o noascii.o nobinary.o nofilesz.o mallocdb.o"
CRT0="crt0.o"
LIBC="libc.a"
