extern void rsrc_init(void);

extern OBJECT ADMENU[];
#define DESKMENU 3
#define FILEMENU 4
#define VIEWMENU 5
#define OPTNMENU 6
#define ABOUITEM 9
#define OPENITEM 18
#define SHOWITEM 19
#define SEAMENU 20
#define DELMENU 22
#define NEWFITEM 24
#define CLSFITEM 25
#define CLSWITEM 26
#define BOTTOP 27
#define SELALL 28
#define EXTMENU 29
#define L3ITEM 30
#define FORMITEM 31
#define ICONITEM 33
#define TEXTITEM 34
#define L4ITEM 35
#define NAMEITEM 36
#define DATEITEM 37
#define SIZEITEM 38
#define TYPEITEM 39
#define NOSORT 40
#define SIZEFIT 42
#define SCOLTYPE 43
#define IDSKITEM 46
#define IAPPITEM 47
#define INSDISK 48
#define REMVICON 49
#define L5ITEM 50
#define PREFITEM 51
#define VIDITEM 52
#define READINF 53
#define MEMMENU 54
#define SAVEITEM 56
extern OBJECT ADFILEIN[];
#define INFTITLE 1
#define FIFILE 2
#define FILEFT 3
#define FIRIGHT 4
#define FINAME 5
#define FISIZE 6
#define FIDATE 7
#define FITIME 8
#define FINFOLDS 9
#define FINFILES 10
#define FIRONLY 11
#define FIRWRITE 12
#define FIATTRS 13
#define FIOK 14
#define FISKIP 15
#define FICNCL 16
extern OBJECT ADDISKIN[];
#define DIDRIVE 2
#define DIVOLUME 3
#define DINFOLDS 4
#define DINFILES 5
#define DIUSED 6
#define DIAVAIL 7
#define DIOK 8
#define DIQUIT 9
extern OBJECT ADDINFO[];
#define DEOK 9
extern OBJECT ADOPENAP[];
#define APPLNAME 1
#define APPLPARM 3
#define APPLOK 4
#define APPLCNCL 5
extern OBJECT ADINSDIS[];
#define DRID 2
#define DRLABEL 3
#define IDRIVE 6
#define ITRASH 7
#define IPRINTER 8
#define IBOX 9
#define IICON 10
#define IUP 11
#define IDOWN 13
#define DROK 14
#define DRCNCL 15
#define DRQUIT 16
extern OBJECT ADMKDBOX[];
#define MKNAME 1
#define MKOK 2
#define MKCNCL 4
extern OBJECT ADFORMAT[];
#define FCBOX4 1
#define FCBOXC 2
#define SRCDRA 4
#define SRCDRB 5
#define DESTDR 6
#define FCCOPY 7
#define LINEBOX 8
#define FCBOXF 9
#define DRIVE 10
#define ADRIVE 11
#define BDRIVE 12
#define FCLABEL 13
#define SIDEBOX 14
#define FCDOUBLE 15
#define FCSINGLE 16
#define FCHIGH 17
#define FCFORMAT 18
#define FCBARA 20
#define FCBARB 22
#define FCOK 23
#define FCCNCL 24
extern OBJECT ADICON[];
#define ICON0 1
#define ICON1 2
#define ICON2 3
#define ICON3 4
#define ICON4 5
extern OBJECT PRINTFIL[];
#define PFILE 1
extern OBJECT BACKGROU[];
extern OBJECT SSCREEN[];
#define STITLE 1
#define DESKPREF 4
#define WINPREF 5
#define PAT0 9
#define PAT1 10
#define PAT2 11
#define PAT3 12
#define PAT4 13
#define PAT5 14
#define PAT6 15
#define PAT7 16
#define OUTBOX 17
#define PATTERN 18
#define COLOR0 20
#define COLOR1 21
#define COLOR2 22
#define COLOR3 23
#define COLOR4 24
#define COLOR5 25
#define COLOR6 26
#define COLOR7 27
#define COLOR8 28
#define COLOR9 29
#define COLOR10 30
#define COLOR11 31
#define COLOR12 32
#define COLOR13 33
#define COLOR14 34
#define COLOR15 35
#define SOK 36
#define SCANCEL 37
extern OBJECT FILEOPTI[];
#define OPTNAME 2
#define OPTOK 3
extern OBJECT DLAUNCH[];
#define RUNNAME 2
#define LTOS 4
#define LGRAPHIC 5
#define LAUNCHOK 7
#define LNCNCL 8
extern OBJECT TEXTLINE[];
#define TSTYLE 1
extern OBJECT SAMENAME[];
#define SNAME 1
#define FNAME 2
#define EDFNAME 3
#define COPY 4
#define SKIP 5
#define QUIT 6
extern OBJECT CPBOX[];
#define TITLE 1
#define NUMDIR 2
#define NUMFILE 3
#define CSDRIVE 4
#define CDDRIVE 5
#define HIDECBOX 6
#define CPFILE 7
#define CPDIR 8
#define DATEBOX 9
#define PYES 11
#define CHBOX1 13
#define OKCP 14
#define CCANCEL 15
extern OBJECT INWICON[];
#define IBOX1 2
#define WNAME 3
#define WBOX 5
#define WICON 6
#define WUP 7
#define WDOWN 8
#define WFOLDER 10
#define WNONE 11
#define WSKIP 12
#define WREMOVE 13
#define WOK 14
#define WQUIT 16
extern OBJECT HELP1[];
#define MOREHELP 14
extern OBJECT HELP2[];
extern OBJECT SEAFILE[];
#define SFILE 2
#define SEAOK 3
#define SEACNCL 4
extern OBJECT MNINSAPP[];
#define MPFNAME 2
#define MPARGS 3
#define MPDTYPE 4
#define MPITITLE 5
#define MPIBUTTN 6
#define MPBTITLE 7
#define MPBBUTTN 8
#define MPFTITLE 9
#define MPFBUTTN 10
#define MPDTITLE 11
#define MPDBUTTN 12
#define MPPTITLE 13
#define MPPBUTTN 14
#define MPOK 15
#define MPREMOVE 16
#define MPCANCEL 17
#define MPQUIT 18
extern OBJECT MNSETPRE[];
#define SPDTITLE 3
#define SPDBUTTN 4
#define SPCTITLE 5
#define SPCBUTTN 6
#define SPOTITLE 7
#define SPOBUTTN 8
#define MNSPOK 9
#define MNSPCAN 10
extern OBJECT MNSETVID[];
#define SVCTITLE 2
#define SVCBUTTN 3
#define SVLTITLE 4
#define SVLBUTTN 5
#define SVDTITLE 6
#define SVDBUTTN 7
#define SVMODES 8
#define IBASE 9
#define SVOK 10
#define SVCANCEL 11
extern OBJECT MNVIDEO[];
#define SVSTLOW 3
#define SVSTMED 4
#define SVSTHIGH 5
#define SVTTOK 6
#define SVTTCAN 7
extern OBJECT MNMENU[];
#define MPIBASE 1
#define MPINONE 2
#define MPIF1 3
#define MPIF2 4
#define MPIF3 5
#define MPIF4 6
#define MPIF5 7
#define MPIF6 8
#define MPIF7 9
#define MPIF8 10
#define MPIF9 11
#define MPIF10 12
#define MPFI11 13
#define MPIF12 14
#define MPIF13 15
#define MPIF14 16
#define MPIF15 17
#define MPIF16 18
#define MPIF17 19
#define MPIF18 20
#define MPIF19 21
#define MPIF20 22
#define MPFBASE 23
#define MPFTOS 24
#define MPFTTP 25
#define MPFGEM 26
#define MPFGMTTP 27
#define SDBASE 28
#define SDAPP 29
#define SDTOP 30
#define SIBASE 31
#define SIFULL 32
#define SIFILE 33
#define MPBBASE 34
#define MPBAUTO 35
#define MPBNORML 36
#define SPBASE 37
#define SPYES 38
#define SPNO 39
#define VIDBASE 40
#define VID2 41
#define VID4 42
#define VID16 43
#define VID256 44
#define VIDTRUE 45
#define SVIBASE 46
#define SVION 47
#define SVIOFF 48
#define SVLBASE 49
#define SVL40 50
#define SVL80 51
extern OBJECT MNSYSTEM[];
#define SDTITLE 2
#define SDBUTTON 3
#define SITITLE 4
#define SIBUTTON 5
#define MFBASE 7
#define MFLEFT 8
#define MFFILE 9
#define MFRIGHT 10
#define MFKEY 11
#define MFUP 12
#define MFDOWN 13
#define MKITEM 17
#define MKUPS 18
#define MKDOWNS 19
#define MKKEYS 20
#define MKCLEAR 21
#define MKMEMORY 22
#define MOK 23
#define MCANCEL 24
extern char MORE[];
extern char ENDFILE[];
extern char CART[];
extern char CPYSTR[];
extern char DELSTR[];
extern char FILEINFO[];
extern char FOLDINFO[];
extern char MOVESTR[];
extern char READERRO[];
extern char CANTOPEN[];
extern char NOMEM[];
extern char CACHETXT[];
extern char BLTTXT[];
extern char NCONFLIC[];
extern char RNAME[];
extern char CRENSTR[];
extern char MRENSTR[];
extern char ISTR[];
extern char ISELS[];
extern char ISEL[];
extern char ISTRS[];
extern char DEVICE[];
extern char SINF[];
extern char LITEM[];
extern char FSTOS[];
extern char FSTOSTTP[];
extern char FSGEM[];
extern char FSGEMTTP[];
extern char FSAPP[];
extern char FSTOP[];
extern char FSFULL[];
extern char FSFILE[];
extern char FS40[];
extern char FS80[];
extern char FSYES[];
extern char FSNO[];
extern char FS2C[];
extern char FS4C[];
extern char FS16C[];
extern char FS256C[];
extern char FSTRUEC[];
extern char FSAUTO[];
extern char FSNORMAL[];
extern char FSON[];
extern char FSOFF[];
extern char FSNONE[];
extern char FSF1[];
extern char FSF2[];
extern char FSF3[];
extern char FSF4[];
extern char FSF5[];
extern char FSF6[];
extern char FSF7[];
extern char FSF8[];
extern char FSF9[];
extern char FSF10[];
extern char FSF11[];
extern char FSF12[];
extern char FSF13[];
extern char FSF14[];
extern char FSF15[];
extern char FSF16[];
extern char FSF17[];
extern char FSF18[];
extern char FSF19[];
extern char FSF20[];
extern char DLTEXT[];
extern char ITEXT[];
extern char STNOAPPL[];
extern char STNOWIND[];
extern char STFOEXIS[];
extern char STDISKFU[];
extern char STFO8DEE[];
extern char STBADCOP[];
extern char TRSINFO[];
extern char FCNOMEM[];
extern char FCFAIL[];
extern char FCSIZE[];
extern char FCNOTYPE[];
extern char SAVETOP[];
extern char PRINTTOP[];
extern char ABORTCON[];
extern char NOICON[];
extern char NOAPP[];
extern char NODRIVE[];
extern char NOOUTPUT[];
extern char CNTOPEN[];
extern char CNTCRTDR[];
extern char WRERROR[];
extern char RDERROR[];
extern char CNTCRTFL[];
extern char CNTDELF[];
extern char CNTDELD[];
extern char PRINTINF[];
extern char RENAME[];
extern char NOBUF[];
extern char DELDISK[];
extern char NOTPRG[];
extern char NOSETDIR[];
extern char NOAUTO[];
extern char NOWINMEM[];
extern char NOTYPE[];
extern char ICONTYPE[];
extern char NODIRCOP[];
extern char NOINSTAL[];
extern char NOMORE[];
extern char NOID[];
extern char ILLMAT[];
extern char NOCART[];
extern char NOMATCH[];
extern char DELITEM[];
extern char MCFAIL[];
extern char FNOTFIND[];
extern char SNEXT[];
extern char NOHELP[];
extern char NOSEA[];
extern char KEYUSED[];
extern char CARTNOSH[];
extern char BADKEY[];
extern char XNFILE[];
