#!/bin/sh

BIN=../bin64/
LIB=../lib

compile=false
preproc=false
outfile=
infile=
CPPFLAGS=
CFLAGS=-f
LDFLAGS=
ASFLAGS="-u -L -s ${LIB}"
undefined=false
nolocals=false
absolute=false
symbols=false
textbase=
database=
bssbase=

while test "$1" != ""
do
	arg="$1"
	shift
	case $arg in
	-c) compile=true ;;
	-E) preproc=true ;;
	-P) ;;
	-o)
		outfile=$1
		shift
		;;
	-O2) ;;
	-fomit-frame-pointer) ;;
	-a)
	     textbase=$1
	     shift
	     database=$1
	     shift
	     bssbase=$1
	     shift
	     ;;
	-u)
	     undefined=true
	     ;;
        -l)  nolocals=true
             ;;
	-s)  symbols=true
             ;;
	-W*) ;;
	-I)
	     CPPFLAGS="$CPPFLAGS -I $1"
	     shift
	     ;;
	-I*) CPPFLAGS="$CPPFLAGS $arg" ;;
	-D*) CPPFLAGS="$CPPFLAGS $arg" ;;
	*) infile="$infile $arg"
	esac
done

if test "$infile" = ""; then
	echo "no input files" >&2
	exit 1
fi

status=1
if $compile; then
	case $infile in
	*.c)
		base=$(basename $infile .c)
		if ${BIN}cp68 ${CPPFLAGS} ${infile} ${base}.i; then
			if ${BIN}c068 ${base}.i ${base}.1 ${base}.2 ${base}.3 ${CFLAGS}; then
				if ${BIN}c168 ${base}.1 ${base}.2 ${base}.s; then
					if ${BIN}optimize -q ${base}.s; then
						if ${BIN}as68 ${ASFLAGS} ${base}.s; then
							status=0
						fi
					fi
				fi
			fi
		fi
		rm -f ${base}.s ${base}.i ${base}.1 ${base}.2 ${base}.3
		;;
	*.S)
		base=$(basename $infile .S)
		if ${BIN}cp68 ${CPPFLAGS} -P ${infile} ${base}.i; then
			if ${BIN}as68 ${ASFLAGS} ${base}.i; then
				status=0
			fi
		fi
		rm -f ${base}.i
		;;
	esac
elif $preproc; then
	if test "$outfile" = ""; then
		echo "no output file" >&2
		exit 1
	fi
	if ${BIN}cp68 ${CPPFLAGS} -P ${infile} ${outfile}; then
		status=0
	fi
else
	if test "$outfile" = ""; then
		echo "no output file" >&2
		exit 1
	fi
	if test "$infile" = ""; then
		echo "no input files" >&2
		exit 1
	fi
	LDFLAGS=
	if $undefined; then
		LDFLAGS="${LDFLAGS}un,"
	fi
	if $nolocals; then
		LDFLAGS="${LDFLAGS}no,"
	fi
	if $symbols; then
		LDFLAGS="${LDFLAGS}sy,"
	fi
	if test "$textbase" != ""; then
		LDFLAGS="${LDFLAGS}text[$textbase],"
	fi
	if test "$database" != ""; then
		LDFLAGS="${LDFLAGS}data[$database],"
	fi
	if test "$bssbase" != ""; then
		LDFLAGS="${LDFLAGS}bss[$bssbase],"
	fi
	LDFLAGS=$(echo $LDFLAGS | sed -e 's/,$//')
	infile=$(echo $infile | tr ' ' ',')
	if ${BIN}link68 [${LDFLAGS}] ${outfile}=${infile}; then
		status=0
	fi
fi



exit $status
